num_epochs: 5
batch_size: 2
learning_rate: 0.00015
min_lr: 0.000001
weight_decay: 0.05
gradient_clip: 1.0
seed: 42
val_interval: 1
save_interval: 5
checkpoint_dir: ${output.checkpoint_dir}
resume: null
