num_epochs: 120
batch_size: 32
accumulation_steps: 2
learning_rate: 0.00032
min_lr: 0.000003
weight_decay: 0.05
gradient_clip: 1.0
seed: 42
val_interval: 10
save_interval: 50
checkpoint_dir: ${output.checkpoint_dir}
resume: null

# Optimization options
use_amp: true
use_compile: false
fused_optimizer: true
gradient_checkpointing: true
