num_epochs: 200
batch_size: 8
learning_rate: 0.00015
min_lr: 0.000001
weight_decay: 0.05
gradient_clip: 1.0
seed: 42
val_interval: 10
save_interval: 50
checkpoint_dir: ${output.checkpoint_dir}
resume: null
