num_epochs: 100
batch_size: 80
accumulation_steps: 1
learning_rate: 0.0008
min_lr: 0.00001
weight_decay: 0.05
gradient_clip: 1.0
seed: 42
val_interval: 10
save_interval: 50
checkpoint_dir: ${output.checkpoint_dir}
resume: null

# Optimization options
use_amp: true
use_compile: false
fused_optimizer: true
gradient_checkpointing: true
