tensorboard_dir: ${output.tensorboard_dir}
log_interval: 10
wandb:
    enable: true
    mode: ${oc.env:WANDB_MODE,online}
    project: null
    entity: null
    run_name: ${hydra:job.name}
    group: ${hydra:job.override_dirname}
    notes: ""
    tags: []
    watch:
        log: gradients
        log_freq: 200
    log_checkpoints: true
    log_results: true
    log_visualizations: true
    visualization_interval: 1
    max_visualizations: 4

# Reconstruction visualization settings
reconstruction_vis:
    enable: true
    interval: 1 # Every epoch
    num_samples: 5 # Number of fixed samples to track
    metrics:
        - psnr
        - ssim
        - mse
        - mae
    visualizations:
        - comparison_grid # Original/Masked/Recon/Diff
        - temporal_sequence # Full temporal sequence
        - error_heatmap # Error heatmap
